### ISSUE TITLE
Cannot copy data from repeating events

### ISSUE THREAD

**Issue by Fran7654321** [lsgs/redcap-copy-data-on-save#7]
I have this project with really important repeating events and I need to copy everyone to another project, but with this module  I just get copy the first one... I dont know how to trigger the copy for every repeating instance!!

**Comment by lsgs** [comment]
@Fran7654321 - you should find that when you save a form in a repeating event in the source project that it will copy the data from the saved instance to a matching instance number in the destination project (assuming fields are on a repeating event/form in the destination). 

Could it be that the form you are using to trigger the copy is not repeating, but you have got the configuration set to copy some fields from a repeating form? If so then it is expected behaviour that you would only ever get data from instance #1 of those fields.
